<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "category".
 *
 * @property integer $id
 * @property string $name
 * @property string $alias
 * @property string $seo_title
 * @property string $seo_keywords
 * @property string $seo_h1
 * @property string $seo_description
 * @property string $image
 * @property string $description
 * @property string $aliasModel
 */
abstract class Category extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'category';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'description'], 'required'],
            [['seo_description', 'description'], 'string'],
            [['name', 'alias', 'seo_title', 'seo_keywords', 'seo_h1', 'image'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'alias' => 'Урл',
            'seo_title' => 'Seo Title',
            'seo_keywords' => 'Seo Keywords',
            'seo_h1' => 'Seo H1',
            'seo_description' => 'Seo Description',
            'image' => 'Изображение(427x550)',
            'description' => 'Описание',
        ];
    }




}
