<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "designer".
 *
 * @property integer $id
 * @property string $name
 * @property string $alias
 * @property string $product_text
 * @property string $text
 * @property string $image
 * @property string $studio
 * @property string $address
 * @property string $phone1
 * @property string $phone2
 * @property string $email
 * @property string $site
 * @property string $seo_title
 * @property string $seo_keywords
 * @property string $seo_h1
 * @property string $seo_description
 * @property integer $show_on_page
 * @property string $aliasModel
 */
abstract class Designer extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'designer';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'text'], 'required'],
            [['product_text', 'text', 'seo_description'], 'string'],
            [['show_on_page'], 'integer'],
            [['name', 'alias', 'image', 'studio', 'address', 'phone1', 'phone2', 'email', 'site', 'seo_title', 'seo_keywords', 'seo_h1'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'alias' => 'Урл',
            'product_text' => 'Текст объекта',
            'text' => 'Текст',
            'image' => 'Изображение(284x284)',
            'studio' => 'Студия',
            'address' => 'Адрес',
            'phone1' => 'Телефон1',
            'phone2' => 'Телефон2',
            'email' => 'E-mail',
            'site' => 'Сайт',
            'seo_title' => 'Seo Title',
            'seo_keywords' => 'Seo Keywords',
            'seo_h1' => 'Seo H1',
            'seo_description' => 'Seo Description',
            'show_on_page' => 'Показывать на странице?',
        ];
    }




}
