<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "event".
 *
 * @property integer $id
 * @property string $name
 * @property integer $date
 * @property string $text
 * @property string $image
 * @property string $alias
 * @property string $seo_title
 * @property string $seo_keywords
 * @property string $seo_h1
 * @property string $seo_description
 * @property string $aliasModel
 */
abstract class Event extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'event';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'date', 'text', 'image'], 'required'],
            [['date'], 'integer'],
            [['text', 'seo_description'], 'string'],
            [['name', 'image', 'alias', 'seo_title', 'seo_keywords', 'seo_h1'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'date' => 'Дата',
            'text' => 'Текст',
            'image' => 'Изображение(1200x400)',
            'alias' => 'Урл',
            'seo_title' => 'Seo Title',
            'seo_keywords' => 'Seo Keywords',
            'seo_h1' => 'Seo H1',
            'seo_description' => 'Seo Description',
        ];
    }




}
