<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "mainpage".
 *
 * @property integer $id
 * @property string $name
 * @property string $seo_title
 * @property string $seo_keywords
 * @property string $seo_description
 * @property string $aliasModel
 */
abstract class Mainpage extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'mainpage';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['seo_description'], 'string'],
            [['name', 'seo_title', 'seo_keywords'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'seo_title' => 'Seo Title',
            'en_seo_title' => 'En Seo Title',
            'seo_keywords' => 'Seo Keywords',
        ];
    }




}
