<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "partner".
 *
 * @property integer $id
 * @property string $name
 * @property string $alias
 * @property string $image
 * @property string $site1
 * @property string $site2
 * @property string $text
 * @property string $seo_title
 * @property string $seo_keywords
 * @property string $seo_h1
 * @property string $seo_description
 * @property string $aliasModel
 */
abstract class Partner extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'partner';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'site1', 'text'], 'required'],
            [['text', 'seo_description'], 'string'],
            [['name', 'alias', 'image', 'site1', 'site2', 'seo_title', 'seo_keywords', 'seo_h1'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'alias' => 'Урл',
            'image' => 'Изображение(maxWidth - 380px, maxHeight - 110px)',
            'site1' => 'Сайт1',
            'site2' => 'Сайт2',
            'text' => 'Текст',
            'seo_title' => 'Seo Title',
            'seo_keywords' => 'Seo Keywords',
            'seo_h1' => 'Seo H1',
            'seo_description' => 'Seo Description',
        ];
    }




}
