<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "product".
 *
 * @property integer $id
 * @property string $name
 * @property string $alias
 * @property string $object
 * @property integer $area
 * @property integer $realization
 * @property string $type
 * @property string $image1
 * @property string $image2
 * @property string $image3
 * @property string $image4
 * @property string $image5
 * @property string $image6
 * @property string $image7
 * @property string $image8
 * @property string $image9
 * @property string $image10
 * @property string $image11
 * @property string $image12
 * @property string $image13
 * @property string $image14
 * @property string $image15
 * @property string $image16
 * @property string $image_small1
 * @property string $image_small2
 * @property string $image_small3
 * @property string $image_small4
 * @property string $image_small5
 * @property string $image_small6
 * @property string $image_small7
 * @property string $image_small8
 * @property string $image_small9
 * @property string $image_small10
 * @property string $image_small11
 * @property string $image_small12
 * @property string $image_small13
 * @property string $image_small14
 * @property string $image_small15
 * @property string $image_small16
 * @property string $slider_image1
 * @property string $slider_image2
 * @property string $slider_image3
 * @property string $slider_image4
 * @property string $slider_image5
 * @property string $slider_image_small2
 * @property string $slider_image_small4
 * @property string $slider_image_small3
 * @property string $slider_image_small1
 * @property string $slider_image_small5
 * @property string $block1_text
 * @property string $block1_author
 * @property string $block1_function
 * @property string $block2_text
 * @property string $block2_author
 * @property string $block2_function
 * @property string $block3_text
 * @property string $block3_author
 * @property string $block3_function
 * @property string $plan
 * @property string $category_id
 * @property string $designer_id
 * @property string $designer2_id
 * @property string $support
 * @property string $seo_title
 * @property string $seo_keywords
 * @property string $seo_h1
 * @property string $seo_description
 * @property string $aliasModel
 */
abstract class Product extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'object', 'area', 'realization', 'type', 'block1_text', 'block2_text', 'block3_text', 'category_id', 'designer_id'], 'required'],
            [['area', 'realization'], 'integer'],
            [['block1_text', 'block2_text', 'block3_text', 'seo_description'], 'string'],
            [['name', 'alias', 'object', 'type', 'image1', 'image2', 'image3', 'image4', 'image5', 'image6', 'image7', 'image8', 'image9', 'image10', 'image11', 'image12', 'image13', 'image14', 'image15', 'image16', 'image_small1', 'image_small2', 'image_small3', 'image_small4', 'image_small5', 'image_small6', 'image_small7', 'image_small8', 'image_small9', 'image_small10', 'image_small11', 'image_small12', 'image_small13', 'image_small14', 'image_small15', 'image_small16', 'slider_image1', 'slider_image2', 'slider_image3', 'slider_image4', 'slider_image5', 'slider_image_small2', 'slider_image_small4', 'slider_image_small3', 'slider_image_small1', 'slider_image_small5', 'block1_author', 'block1_function', 'block2_author', 'block2_function', 'block3_author', 'block3_function', 'plan', 'category_id', 'designer_id', 'designer2_id', 'support', 'seo_title', 'seo_keywords', 'seo_h1'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'alias' => 'Урл',
            'object' => 'Объект',
            'area' => 'Общая площадь (м2)',
            'realization' => 'Реализация (год)',
            'type' => 'Тип объекта',
            'image1' => 'Изображение1(ширина и высота не более 1500px)',
            'image2' => 'Изображение2(ширина и высота не более 1500px)',
            'image3' => 'Изображение3(ширина и высота не более 1500px)',
            'image4' => 'Изображение4(ширина и высота не более 1500px)',
            'image5' => 'Изображение5(ширина и высота не более 1500px)',
            'image6' => 'Изображение6(ширина и высота не более 1500px)',
            'image7' => 'Изображение7(ширина и высота не более 1500px)',
            'image8' => 'Изображение8(ширина и высота не более 1500px)',
            'image9' => 'Изображение9(ширина и высота не более 1500px)',
            'image10' => 'Изображение10(ширина и высота не более 1500px)',
            'image11' => 'Изображение11(ширина и высота не более 1500px)',
            'image12' => 'Изображение12(ширина и высота не более 1500px)',
            'image13' => 'Изображение13(ширина и высота не более 1500px)',
            'image14' => 'Изображение14(ширина и высота не более 1500px)',
            'image15' => 'Изображение15(ширина и высота не более 1500px)',
            'image16' => 'Изображение16(ширина и высота не более 1500px)',
            'image_small1' => 'Изображение миниатюра1(426x426)',
            'image_small2' => 'Изображение миниатюра2(426x426)',
            'image_small3' => 'Изображение миниатюра3(426x426)',
            'image_small4' => 'Изображение миниатюра4(426x426)',
            'image_small5' => 'Изображение миниатюра5(426x426)',
            'image_small6' => 'Изображение миниатюра6(426x426)',
            'image_small7' => 'Изображение миниатюра7(426x426)',
            'image_small8' => 'Изображение миниатюра8(426x426)',
            'image_small9' => 'Изображение миниатюра9(426x426)',
            'image_small10' => 'Изображение миниатюра10(426x426)',
            'image_small11' => 'Изображение миниатюра11(426x426)',
            'image_small12' => 'Изображение миниатюра12(426x426)',
            'image_small13' => 'Изображение миниатюра13(426x426)',
            'image_small14' => 'Изображение миниатюра14(426x426)',
            'image_small15' => 'Изображение миниатюра15(426x426)',
            'image_small16' => 'Изображение миниатюра16(426x426)',
            'slider_image1' => 'Слайд1(ширина и высота не более 1500px)',
            'slider_image2' => 'Слайд2(ширина и высота не более 1500px)',
            'slider_image3' => 'Слайд3(ширина и высота не более 1500px)',
            'slider_image4' => 'Слайд4(ширина и высота не более 1500px)',
            'slider_image5' => 'Слайд5(ширина и высота не более 1500px)',
            'slider_image_small2' => 'Слайд миниатрюра2(950x540)',
            'slider_image_small4' => 'Слайд миниатрюра4(950x540)',
            'slider_image_small3' => 'Слайд миниатрюра3(950x540)',
            'slider_image_small1' => 'Слайд миниатрюра1(950x540)',
            'slider_image_small5' => 'Слайд миниатрюра5(950x540)',
            'block1_text' => 'Центр центр текст',
            'block1_author' => 'Центр центр автор',
            'block1_function' => 'Центр центр кто',
            'block2_text' => 'Низ левый текст',
            'block2_author' => 'Низ левый автор',
            'block2_function' => 'Низ левый кто',
            'block3_text' => 'Низ правый текст',
            'block3_author' => 'Низ правый автор',
            'block3_function' => 'Низ правый кто',
            'plan' => 'План объекта(ширина и высота не более 1500px)',
            'category_id' => 'Категория',
            'designer_id' => 'Дизайнер',
            'designer2_id' => 'Дизайнер 2',
            'support' => 'При поддержке',
            'seo_title' => 'Seo Title',
            'seo_keywords' => 'Seo Keywords',
            'seo_h1' => 'Seo H1',
            'seo_description' => 'Seo Description',
        ];
    }




}
